

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8713
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/practice?serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true   #驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml  #指定xml文件的地址